// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "controllers/application"

import ArtistRowsController from "controllers/artist_rows_controller"
application.register("artist-rows", ArtistRowsController)

import AutocompleteController from "controllers/autocomplete_controller"
application.register("autocomplete", AutocompleteController)

import DatePickerController from "controllers/date_picker_controller"
application.register("date-picker", DatePickerController)

import DropdownController from "controllers/dropdown_controller"
application.register("dropdown", DropdownController)

import ItemFormController from "controllers/item_form_controller"
application.register("item-form", ItemFormController)

import LinkTitleSuggestController from "controllers/link_title_suggest_controller"
application.register("link-title-suggest", LinkTitleSuggestController)

import MarkdownPreviewController from "controllers/markdown_preview_controller"
application.register("markdown-preview", MarkdownPreviewController)

import MobileMenuController from "controllers/mobile_menu_controller"
application.register("mobile-menu", MobileMenuController)

import PersonSelectController from "controllers/person_select_controller"
application.register("person-select", PersonSelectController)

import SearchSuggestController from "controllers/search_suggest_controller"
application.register("search-suggest", SearchSuggestController)

import SortableController from "controllers/sortable_controller"
application.register("sortable", SortableController)

import TagGroupSelectController from "controllers/tag_group_select_controller"
application.register("tag-group-select", TagGroupSelectController)

import TimelineController from "controllers/timeline_controller"
application.register("timeline", TimelineController)

import TimelineSearchController from "controllers/timeline_search_controller"
application.register("timeline-search", TimelineSearchController)

import ToggleController from "controllers/toggle_controller"
application.register("toggle", ToggleController)

import UnitGraphController from "controllers/unit_graph_controller"
application.register("unit-graph", UnitGraphController)

import UnitSelectController from "controllers/unit_select_controller"
application.register("unit-select", UnitSelectController)

import YoutubeCarouselController from "controllers/youtube_carousel_controller"
application.register("youtube-carousel", YoutubeCarouselController)
