// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "controllers/application"

import ArtistRowsController from "controllers/artist_rows_controller"
application.register("artist-rows", ArtistRowsController)

import AutocompleteController from "controllers/autocomplete_controller"
application.register("autocomplete", AutocompleteController)

import DatePickerController from "controllers/date_picker_controller"
application.register("date-picker", DatePickerController)

import DropdownController from "controllers/dropdown_controller"
application.register("dropdown", DropdownController)

import MobileMenuController from "controllers/mobile_menu_controller"
application.register("mobile-menu", MobileMenuController)

import SearchSuggestController from "controllers/search_suggest_controller"
application.register("search-suggest", SearchSuggestController)

import PersonSelectController from "controllers/person_select_controller"
application.register("person-select", PersonSelectController)

import SortableController from "controllers/sortable_controller"
application.register("sortable", SortableController)

import ToggleController from "controllers/toggle_controller"
application.register("toggle", ToggleController)

import MarkdownPreviewController from "controllers/markdown_preview_controller"
application.register("markdown-preview", MarkdownPreviewController)
