inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'app/views/**/*'
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'vendor/**/*'
    - 'node_modules/**/*'

Metrics/BlockLength:
  Exclude:
    - 'lib/tasks/import_wikipage.rb'

Metrics/ClassLength:
  Exclude:
    - 'app/models/person.rb'
